Ported a large part of LLVMCompiler.cpp to slua_compiler.c

diff --git a/compiler/slua-compiler.in b/compiler/slua-compiler.in
--- a/compiler/slua-compiler.in
+++ b/compiler/slua-compiler.in
@@ -8,19 +8,17 @@ DIR=`dirname $DIR`
 CC=gcc
 LIBTOOL="libtool --tag=CC --silent"
 RPATH=`pwd`
-LLVM_LUAC="./llvm-luac"
+SLUAC="./sluac"
 PREFIX="@CMAKE_INSTALL_PREFIX@"
 
-# find llvm-luac
-if [[ ! -x "$LLVM_LUAC" ]]; then
-	LLVM_LUAC="$DIR/llvm-luac"
+# find sluac
+if [[ ! -x "$SLUAC" ]]; then
+	SLUAC="$DIR/sluac"
 fi
-if [[ ! -x "$LLVM_LUAC" ]]; then
-	LLVM_LUAC=`which llvm-luac`
+if [[ ! -x "$SLUAC" ]]; then
+	SLUAC=`which sluac`
 fi
 
-TARGET=
-FORCE_TARGET="0"
 CPU=i686
 #CPU=pentium4
 #CPU=athlon64
@@ -31,12 +29,12 @@ OUTPUT_FILE=""
 DEBUG="0"
 KEEP_TMPS="0"
 STATIC="0"
-MODE="full_bc"
+MODE="standalone"
 EXTRA_ARGS=
 LIBS=
 
 function version() {
-	$LLVM_LUAC -version
+	$SLUAC -version
 	exit 0;
 }
 
@@ -52,25 +50,13 @@ OPTIONS:
                        info and gcc debug symbols are enabled.
   -keep-tmps       - Don't delete temp. files generated by intermediate stages.  Use only
                        for debuging generated code or if you are really curious!
-  -target=<target> - <target> is passed to llc as '-target=<target>', see llc --version for targets
   -mcpu=<arch>     - <cpu> is passed to gcc as '-march=<cpu>'
-  -mode=<mode>     - Switch how LLVM bitcode is generated and compiled into native code.
-                   -   full_bc - (default mode) compiles Lua scripts into LLVM bitcode
-                         linked with bitcode liblua_main.bc then converted to assembly
-                         before being compiled with gcc to a native executable.
-                   -   lua_mod - Only used by the '-lua-module' option.  Don't use
-                         it directly.
-                   The following modes are for testing only:
-                   -   cbe - compile Lua script into C-code from LLVM bitcode, then use
-                         gcc to compile to native executable binary.
-                   -   c - compiles Lua scripts into C-code.
-                   -   ll - compiles Lua scripts into LLVM IR code.
-  -******          - All other options passed to 'llvm-luac'.  See below for a list of
-                       options supported by 'llvm-luac'.
+  -******          - All other options passed to 'sluac'.  See below for a list of
+                       options supported by 'sluac'.
 
-llvm-luac '-help' output:
+sluac '-help' output:
 "
-	$LLVM_LUAC -help
+	$SLUAC -help
 	exit 0;
 }
 
@@ -92,7 +78,6 @@ for arg in "$@" ; do
 	-debug)  DEBUG="1" ;;
 	-keep-tmps)  KEEP_TMPS="1" ;;
 	-mode=*)  MODE=` echo "$arg" | sed -e 's/-mode=//'` ;;
-	-target=*)  FORCE_TARGET="1"; TARGET=` echo "$arg" | sed -e 's/-target=//'` ;;
 	-mcpu=*)  FORCE_CPU="1"; CPU=` echo "$arg" | sed -e 's/-mcpu=//'` ;;
 	-help|--help|-h)  usage ;;
 	-version|--version|-v)  version ;;
@@ -107,7 +92,6 @@ done
 OUTPUT_EXT=""
 case "$MODE" in
 	c) OUTPUT_EXT=".c" ;;
-	ll) OUTPUT_EXT=".ll" ;;
 	lua_mod) OUTPUT_EXT=".so" ;;
 esac
 if [[ -z "$OUTPUT_FILE" ]]; then
@@ -126,8 +110,6 @@ if [[ $DEBUG == "1" ]]; then
 	LUA_FLAGS=" -O0 -g "
 	#LUA_FLAGS=" -O3 -do-not-inline-opcodes "
 	#CFLAGS=" -ggdb -O3 -fomit-frame-pointer -pipe -Wall "
-	OPT_FLAGS=" -disable-opt "
-	LLC_FLAGS=" "
 	if [[ ! -z $CPU && $FORCE_CPU == "1" ]]; then
 		CFLAGS=" -march=$CPU $CFLAGS "
 	fi
@@ -139,11 +121,6 @@ else
 	if [[ ! -z $CPU ]]; then
 		CFLAGS=" -march=$CPU $CFLAGS "
 	fi
-	OPT_FLAGS=" -O3 -std-compile-opts -tailcallelim -tailduplicate "
-	LLC_FLAGS=" -tailcallopt "
-fi
-if [[ ! -z $CPU && $FORCE_CPU == "1" ]]; then
-	LLC_FLAGS=" -mcpu=$CPU $LLC_FLAGS "
 fi
 
 if [[ $MODE == "cbe" ]]; then
@@ -153,65 +130,31 @@ if [[ $MODE == "cbe" ]]; then
 	LIBS="$LIBS -L$DIR -L$DIR/../lib -L$PREFIX/lib "
 elif [[ $MODE == "c" ]]; then
 	EXTRA_ARGS="$EXTRA_ARGS -no-main "
-else
-	# if mode not "cbe" or "c"
-	if [[ ! -z $TARGET && $FORCE_TARGET == "1" ]]; then
-		LLC_FLAGS=" -march=$TARGET $LLC_FLAGS "
-	fi
 fi
 
 #
-# run llvm-luac to compile Lua source/bytecode to LLVM bitcode.
+# run sluac to compile Lua source/bytecode to C code
 #
-echo "$LLVM_LUAC $EXTRA_ARGS $LUA_FLAGS -bc -o ${FILE}.bc ${FILES}"
-$LLVM_LUAC $EXTRA_ARGS $LUA_FLAGS -bc -o ${FILE}.bc ${FILES} || {
-	echo "llvm-luac: failed to compile Lua code into LLVM bitcode."
+echo "$SLUAC $EXTRA_ARGS $LUA_FLAGS -c -o ${FILE}.bc ${FILES}"
+$SLUAC $EXTRA_ARGS $LUA_FLAGS -c -o ${FILE}.c ${FILES} || {
+	echo "sluac: failed to compile Lua code into C code."
 	exit 1;
 }
-TMPS="${FILE}.bc"
+TMPS="${FILE}.c"
 
 # use one of the compile modes.
 case "$MODE" in
-	cbe)
-		TMPS="$TMPS ${FILE}_opt.bc ${FILE}_run.c"
-		echo "opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc"
-		opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc
-		echo "llc $LLC_FLAGS -f --march=c -o ${FILE}_run.c ${FILE}_opt.bc"
-		llc $LLC_FLAGS -f --march=c -o ${FILE}_run.c ${FILE}_opt.bc
-		echo "$CC $CFLAGS $LIBS -o ${OUTPUT_FILE} ${FILE}_run.c -llua_main -lm -ldl"
-		$CC $CFLAGS $LIBS -o ${OUTPUT_FILE} ${FILE}_run.c -llua_main -lm -ldl
-		;;
 	c)
-		TMPS="$TMPS ${FILE}_opt.bc"
-		echo "opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc"
-		opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc
-		echo "llc $LLC_FLAGS -f --march=c -o ${OUTPUT_FILE} ${FILE}_opt.bc"
-		llc $LLC_FLAGS -f --march=c -o ${OUTPUT_FILE} ${FILE}_opt.bc
+		KEEP_TMPS=1
 		;;
-	ll)
-		echo "llvm-dis -f -o ${OUTPUT_FILE} ${FILE}.bc"
-		llvm-dis -f -o ${OUTPUT_FILE} ${FILE}.bc
-		;;
-	full_bc)
-		TMPS="$TMPS ${FILE}_opt.bc ${FILE}_run.bc ${FILE}_run.s"
-		echo "opt $OPT_FLAGS -f -o ${FILE}_run.bc ${FILE}.bc"
-		opt $OPT_FLAGS -f -o ${FILE}_run.bc ${FILE}.bc
-		echo "llc $LLC_FLAGS -f -filetype=asm -o ${FILE}_run.s ${FILE}_run.bc"
-		llc $LLC_FLAGS -f -filetype=asm -o ${FILE}_run.s ${FILE}_run.bc
-		echo "$CC $CFLAGS -o ${OUTPUT_FILE} ${FILE}_run.s -lm -ldl"
-		$CC $CFLAGS -o ${OUTPUT_FILE} ${FILE}_run.s -lm -ldl
+	standalone)
+		echo "$CC $CFLAGS $LIBS -o ${OUTPUT_FILE} ${FILE}.c -llua_main -lm -ldl"
+		$CC $CFLAGS $LIBS -o ${OUTPUT_FILE} ${FILE}.c -llua_main -lm -ldl
 		;;
 	lua_mod)
-		TMPS="$TMPS ${FILE}_opt.bc ${FILE}_mod.s ${FPATH}/${FNAME}.lo ${FPATH}/lib${FNAME}.la"
-		echo "opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc"
-		opt $OPT_FLAGS -f -o ${FILE}_opt.bc ${FILE}.bc
-		echo "llc $LLC_FLAGS -f -filetype=asm -o ${FILE}_mod.s ${FILE}_opt.bc"
-		llc $LLC_FLAGS -f -filetype=asm -o ${FILE}_mod.s ${FILE}_opt.bc || {
-			echo "Error compiling LLVM bitcode to assembly code."
-			exit 1;
-		}
-		# compile assembly code to object file.
-		$LIBTOOL --mode=compile $CC $CFLAGS -c -o ${FILE}.lo ${FILE}_mod.s
+		TMPS="$TMPS ${FPATH}/${FNAME}.lo ${FPATH}/lib${FNAME}.la"
+		# compile C code to lua module.
+		$LIBTOOL --mode=compile $CC $CFLAGS -c -o ${FILE}.lo ${FILE}.c
 		# compile to dynamic module
 		if [[ $STATIC == "0" ]]; then
 			$LIBTOOL --mode=link $CC -rpath ${RPATH} -o ${FPATH}/lib${FNAME}.la ${FILE}.lo && \
